export const CREATE_OWN_COCKTAIL = 'CREATE_OWN_COCKTAIL';
export const REMOVE_OWN_COCKTAIL = 'REMOVE_OWN_COCKTAIL';
export const EDIT_OWN_COCKTAIL = 'EDIT_OWN_COCKTAIL';
export const GET_ITEM_ID = 'GET_ITEM_ID';